Repository terrence-au/aimimi_flutter, pull requests merged in 2021-05, with the labels that each got.

#1 feat: readme
  README.md
Labels: documentation

#4 docs: update readme
  README.md
Labels: documentation

#10 feat: basic structure
  lib/main.dart
  lib/styles/colors.dart
  lib/views/main_view.dart
  lib/views/today_view.dart
  lib/widgets/goal/goal.dart
  lib/widgets/goal/goal_today.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, refactor, style

#11 feat: navbar
  lib/views/main_view.dart
Labels: feature

#12 style: padding for navbar
  lib/views/main_view.dart
Labels: style

#13 Feat/today view
  lib/views/today_view.dart
  lib/widgets/goal/goal_today.dart
Labels: feature

#15 feat: Modify Bottom NavBar
  lib/views/goal_view.dart
  lib/views/leaderboard_view.dart
  lib/views/main_view.dart
  lib/views/profile_view.dart
Labels: feature, refactor

#16 feat: modal and floating button
  assets/Roboto-Black.ttf
  assets/Roboto-BlackItalic.ttf
  assets/Roboto-Bold.ttf
  assets/Roboto-BoldItalic.ttf
  assets/Roboto-Italic.ttf
  assets/Roboto-Light.ttf
  assets/Roboto-LightItalic.ttf
  assets/Roboto-Medium.ttf
  assets/Roboto-MediumItalic.ttf
  assets/Roboto-Regular.ttf
  assets/Roboto-Thin.ttf
  assets/Roboto-ThinItalic.ttf
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-buildRequest.json
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-desc.xcbuild
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-manifest.xcbuild
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-targetGraph.txt
  ios/build/XCBuildData/14be5cfdab49cb755a48d1af1c03076c-buildRequest.json
  ios/build/XCBuildData/14be5cfdab49cb755a48d1af1c03076c-targetGraph.txt
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-buildRequest.json
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-desc.xcbuild
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-manifest.xcbuild
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-targetGraph.txt
  ios/build/XCBuildData/6823029665ec57cf30bfe5a7c0eebb82-buildRequest.json
  ios/build/XCBuildData/6823029665ec57cf30bfe5a7c0eebb82-targetGraph.txt
  ios/build/XCBuildData/810fb9c1f3d085bf3f267e8406e0c4e6-buildRequest.json
  ios/build/XCBuildData/810fb9c1f3d085bf3f267e8406e0c4e6-targetGraph.txt
  ios/build/XCBuildData/BuildDescriptionCacheIndex-dd9c08c6b849b2e574076fbf386c8a6f
  ios/build/XCBuildData/build.db
  ios/build/XCBuildData/c3bddf27286d4c5b9a096bbf03d15227-buildRequest.json
  ios/build/XCBuildData/c3bddf27286d4c5b9a096bbf03d15227-targetGraph.txt
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-buildRequest.json
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-desc.xcbuild
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-manifest.xcbuild
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-targetGraph.txt
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-buildRequest.json
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-desc.xcbuild
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-manifest.xcbuild
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-targetGraph.txt
  ios/build/XCBuildData/eca2793369188a50db0325c5a0de9895-buildRequest.json
  ios/build/XCBuildData/eca2793369188a50db0325c5a0de9895-targetGraph.txt
  lib/main.dart
  lib/styles/colors.dart
  lib/styles/text_fields.dart
  lib/styles/text_styles.dart
  lib/views/main_view.dart
  lib/widgets/modal/modal_add_goal.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#18 feat: Add goal.dart and goal_view.dart.
  lib/views/goal_view.dart
  lib/widgets/goal/goal.dart
Labels: feature

#19 style: bottom nav icon changed for goals
  lib/views/main_view.dart
Labels: style

#20 feat: firebase connection
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  lib/main.dart
  lib/views/main_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#25 fix: podfile ios version
  ios/Podfile
  ios/Podfile.lock
Labels: fix

#27 Feat/mock goals model
  lib/main.dart
  lib/models/goal.dart
  lib/providers/goals_provider.dart
  lib/views/goal_view.dart
  lib/views/main_view.dart
  lib/views/today_view.dart
  lib/widgets/goal/goal_today.dart
  lib/widgets/modal/modal_add_goal.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#28 feat: google sign in, with ios fix
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-desc.xcbuild
  ios/build/XCBuildData/0673738a92290bb85af9362d74bf4aba-manifest.xcbuild
  ios/build/XCBuildData/29f9f028b0c85c42326d7fe78f562943-buildRequest.json
  ios/build/XCBuildData/29f9f028b0c85c42326d7fe78f562943-desc.xcbuild
  ios/build/XCBuildData/29f9f028b0c85c42326d7fe78f562943-manifest.xcbuild
  ios/build/XCBuildData/29f9f028b0c85c42326d7fe78f562943-targetGraph.txt
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-desc.xcbuild
  ios/build/XCBuildData/347c7aab4cb780ee24d9c60d7361a50a-manifest.xcbuild
  ios/build/XCBuildData/BuildDescriptionCacheIndex-dd9c08c6b849b2e574076fbf386c8a6f
  ios/build/XCBuildData/build.db
  ios/build/XCBuildData/d6efd512c0228eade754aac0f3810231-buildRequest.json
  ios/build/XCBuildData/d6efd512c0228eade754aac0f3810231-desc.xcbuild
  ios/build/XCBuildData/d6efd512c0228eade754aac0f3810231-manifest.xcbuild
  ios/build/XCBuildData/d6efd512c0228eade754aac0f3810231-targetGraph.txt
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-desc.xcbuild
  ios/build/XCBuildData/da1b965aec1fca2527e0619fe3dc2892-manifest.xcbuild
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-desc.xcbuild
  ios/build/XCBuildData/e6de2eca4f5fc812dae279627e3098c2-manifest.xcbuild
  ios/build/XCBuildData/e82e16940b5f5b29da990b78a9d6ba2f-buildRequest.json
  ios/build/XCBuildData/e82e16940b5f5b29da990b78a9d6ba2f-desc.xcbuild
  ios/build/XCBuildData/e82e16940b5f5b29da990b78a9d6ba2f-manifest.xcbuild
  ios/build/XCBuildData/e82e16940b5f5b29da990b78a9d6ba2f-targetGraph.txt
  ios/build/XCBuildData/f99b6380352b2bf83e2337c6dfdf06ff-buildRequest.json
  ios/build/XCBuildData/f99b6380352b2bf83e2337c6dfdf06ff-desc.xcbuild
  ios/build/XCBuildData/f99b6380352b2bf83e2337c6dfdf06ff-manifest.xcbuild
  ios/build/XCBuildData/f99b6380352b2bf83e2337c6dfdf06ff-targetGraph.txt
  lib/image/google.png
  lib/main.dart
  lib/providers/google_sign_in.dart
  lib/styles/colors.dart
  lib/views/login_view.dart
  lib/views/profile_view.dart
  lib/widgets/background_painter.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, fix

#29 fix: duplicate package
  pubspec.yaml
Labels: fix

#30 Feat/add a goal
  lib/main.dart
  lib/models/goal.dart
  lib/providers/goals_provider.dart
  lib/services/goal_service.dart
  lib/widgets/modal/modal_add_goal.dart
  pubspec.lock
Labels: feature

#31 feat: stream user's goal (Not under FirebaseAuth StreamBuilder)
  lib/main.dart
  lib/models/user.dart
  lib/providers/google_sign_in.dart
  lib/services/goal_service.dart
  lib/views/login_view.dart
  lib/views/main_view.dart
  lib/views/today_view.dart
  lib/widgets/modal/modal_add_goal.dart
Labels: feature

#32 refactor: files struct and styles
  lib/constants/styles.dart
  lib/main.dart
  lib/providers/goals_provider.dart
  lib/services/goal_service.dart
  lib/styles/colors.dart
  lib/styles/text_fields.dart
  lib/styles/text_styles.dart
  lib/views/goals_view.dart
  lib/views/login_view.dart
  lib/views/main_view.dart
  lib/views/profile_view.dart
  lib/views/today_view.dart
  lib/widgets/goal/goal.dart
  lib/widgets/goal/goal_today.dart
  lib/widgets/modal/modal_add_goal.dart
  lib/widgets/modal/modal_check_in.dart
Labels: refactor

#34 add: dynamic goal view
  lib/models/goal.dart
  lib/views/goals_view.dart
  lib/widgets/goal/goal.dart
Labels: feature

#33 style: not ideal fix for overflow
  lib/widgets/modal/modal_add_goal.dart
Labels: fix, style

#36 refactor: auth provider
  lib/main.dart
  lib/providers/auth.dart
  lib/services/goal_service.dart
  lib/views/login_view.dart
  lib/views/profile_view.dart
  lib/views/signup_view.dart
Labels: refactor

#37 feat: check in goal
  lib/models/user.dart
  lib/services/goal_service.dart
  lib/views/login_view.dart
  lib/views/signup_view.dart
  lib/views/today_view.dart
  lib/widgets/goal/goal_today.dart
  lib/widgets/modal/modal_check_in.dart
Labels: feature, refactor

#38 feat: animated progress
  lib/views/today_view.dart
  lib/widgets/goal/goal_today.dart
Labels: feature, style

#40 feat: leaderboard UI
  lib/models/rank.dart
  lib/views/leaderboard_view.dart
  lib/views/main_view.dart
  lib/widgets/rank/rank.dart
  lib/widgets/rank/rank_top.dart
Labels: feature

#41 Feat/comment view
  ios/build/Runner.build/Debug-iphoneos/Runner.build/dgph
  ios/build/Runner.build/Debug-iphonesimulator/Runner.build/dgph
  lib/constants/styles.dart
  lib/views/activity_view.dart
  lib/views/comment_view.dart
  lib/views/main_view.dart
  lib/widgets/feed/comment.dart
  lib/widgets/feed/comment_title.dart
  lib/widgets/feed/feed.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#48 feat: shares view
  lib/main.dart
  lib/models/goal.dart
  lib/models/user.dart
  lib/services/goal_service.dart
  lib/views/main_view.dart
  lib/views/shares_view.dart
  lib/widgets/goal/goal_shared.dart
Labels: feature

#49 feat: shared goal view
  lib/constants/styles.dart
  lib/main.dart
  lib/models/goal.dart
  lib/models/user.dart
  lib/services/auth_service.dart
  lib/services/goal_service.dart
  lib/views/goal_shared_view.dart
  lib/views/login_view.dart
  lib/views/main_view.dart
  lib/views/profile_view.dart
  lib/views/shares_view.dart
  lib/views/signup_view.dart
  lib/widgets/goal/goal_shared.dart
  lib/widgets/modal/modal_add_goal.dart
  lib/widgets/modal/modal_check_in.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, refactor

#50 Feat/profile
  lib/main.dart
  lib/services/goal_service.dart
  lib/views/profile_view.dart
Labels: feature

#51 Feat/user documents
  lib/main.dart
  lib/services/auth_service.dart
  lib/services/user_document.dart
  lib/views/signup_view.dart
Labels: feature

#52 Feat/dynamic activity view
  lib/main.dart
  lib/models/feed.dart
  lib/models/user.dart
  lib/services/feed_service.dart
  lib/views/activity_view.dart
  lib/views/main_view.dart
  lib/views/shares_view.dart
  lib/widgets/feed/feed.dart
  pubspec.lock
Labels: feature

#53 fix: random fixs
  lib/main.dart
  lib/services/auth_service.dart
  lib/views/profile_view.dart
Labels: fix

#54 feat: search bar
  lib/constants/styles.dart
  lib/main.dart
  lib/services/goal_service.dart
  lib/views/goal_shared_view.dart
  lib/views/shares_view.dart
  lib/widgets/goal/goal_shared.dart
  lib/widgets/modal/modal_add_goal.dart
Labels: feature, style

#55 Feat/leaderboard
  lib/views/leaderboard_view.dart
  lib/widgets/rank/rank_top.dart
Labels: feature

#56 feat: generate feed
  lib/services/auth_service.dart
  lib/services/goal_service.dart
  lib/views/goal_shared_view.dart
  lib/widgets/feed/feed.dart
  lib/widgets/modal/modal_add_goal.dart
  lib/widgets/modal/modal_check_in.dart
Labels: feature

#57 Feat/dynamic comment
  lib/models/feed.dart
  lib/services/feed_service.dart
  lib/views/activity_view.dart
  lib/views/comment_view.dart
  lib/views/main_view.dart
  lib/widgets/feed/comment.dart
  lib/widgets/feed/comment_title.dart
  lib/widgets/feed/feed.dart
Labels: feature

#58 fix: google login
  lib/main.dart
  lib/services/auth_service.dart
Labels: fix

#67 fix: google sign out and sign in on android
  lib/services/auth_service.dart
Labels: fix

#69 style: overflow and scroll view
  lib/views/activity_view.dart
  lib/views/comment_view.dart
  lib/views/goals_view.dart
  lib/views/leaderboard_view.dart
  lib/views/login_view.dart
  lib/views/signup_view.dart
  lib/views/today_view.dart
  lib/widgets/feed/comment_title.dart
  lib/widgets/feed/feed.dart
  lib/widgets/modal/modal_add_goal.dart
Labels: fix, style

#68 Feat/profile pic
  lib/services/auth_service.dart
  lib/services/user_document.dart
  lib/views/activity_view.dart
  lib/widgets/feed/feed.dart
  lib/widgets/rank/rank_top.dart
Labels: feature

#71 feat: recommendation and categories
  lib/main.dart
  lib/services/feed_service.dart
  lib/services/goal_service.dart
  lib/views/goal_shared_view.dart
  lib/views/main_view.dart
  lib/views/shares_view.dart
  lib/widgets/goal/goal_shared.dart
  lib/widgets/modal/modal_add_goal.dart
Labels: feature

#75 feat: ads
  lib/models/ad.dart
  lib/services/ad_service.dart
  lib/views/main_view.dart
  lib/views/shares_view.dart
  lib/widgets/ad/ad.dart
Labels: feature

#76 feat: cloud function
  .firebaserc
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
  lib/widgets/rank/rank.dart
  lib/widgets/rank/rank_top.dart
Labels: feature

#73 feat: quit goal publish goal
  lib/main.dart
  lib/services/goal_service.dart
  lib/views/activity/activity_view.dart
  lib/views/activity/comment_view.dart
  lib/views/auth/login_view.dart
  lib/views/auth/signup_view.dart
  lib/views/goals/goal_view.dart
  lib/views/goals/goals_view.dart
  lib/views/leaderboard/leaderboard_view.dart
  lib/views/main_view.dart
  lib/views/profile/profile_view.dart
  lib/views/shares/goal_shared_view.dart
  lib/views/shares/shares_view.dart
  lib/views/today/today_view.dart
  lib/widgets/feed/comment.dart
  lib/widgets/feed/comment_title.dart
  lib/widgets/feed/feed.dart
  lib/widgets/goal/goal.dart
  lib/widgets/goal/goal_shared.dart
  lib/widgets/goal/goal_today.dart
Labels: feature

#77 fix: minor fix
  lib/views/shares/shares_view.dart
  lib/widgets/background_painter.dart
Labels: fix

#79 build: publish android
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/aimimi.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/aimimi.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/aimimi.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/aimimi.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/aimimi.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: build, feature

#80 fix: leaderboard error on null
  lib/views/shares/goal_shared_view.dart
  lib/views/shares/shares_view.dart
  lib/widgets/ad/ad.dart
  lib/widgets/feed/feed.dart
  lib/widgets/goal/goal_shared.dart
  lib/widgets/rank/rank_top.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#74 fix: listen to display name change event
  lib/services/auth_service.dart
Labels: fix

#81 feat: complete a goal
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  lib/services/goal_service.dart
Labels: feature
